#!/bin/sh
python demo.py -p "./output/LIDC-IDRI-0050/"
python demo.py -p "./output/LIDC-IDRI-0150/"
python demo.py -p "./output/LIDC-IDRI-0250/"
python demo.py -p "./output/LIDC-IDRI-0350/"
python demo.py -p "./output/LIDC-IDRI-0450/"
python demo.py -p "./output/LIDC-IDRI-0100/"
python demo.py -p "./output/LIDC-IDRI-0200/"
python demo.py -p "./output/LIDC-IDRI-0300/"
python demo.py -p "./output/LIDC-IDRI-0400/"
python demo.py -p "./output/LIDC-IDRI-0500/"
python demo.py -p "./output/LIDC-IDRI-0600/"
python demo.py -p "./output/LIDC-IDRI-0700/"
python demo.py -p "./output/LIDC-IDRI-0800/"
python demo.py -p "./output/LIDC-IDRI-0900/"
python demo.py -p "./output/LIDC-IDRI-1000/"
